#!/bin/bash

if [ -z "$1" ]; then
	echo 'Gimme a command, Dummy'
else
	if [ "$1" == "run" ]; then
		python3 manage.py runserver
	elif [ "$1" == "migrate" ]; then
		python3 manage.py migrate
	elif [ "$1" == "makemigrations" ]; then
		if [ -z "$2" ]; then
			echo "Tell me what you're migrating, Dummy"
		else
			python3 manage.py makemigrations $2
		fi
	fi
fi
